import fs from 'node:fs';
import {JSDOM} from 'jsdom';
import svgpath from 'svgpath';
const names=JSON.parse(fs.readFileSync('design/redesign/assignments/nature.json')).map(x=>x.name), bad=[];
function points(d,transform){let points=[],x=0,y=0,sx=0,sy=0;svgpath(d).transform(transform).abs().unshort().unarc().iterate(s=>{let c=s[0],ox=x,oy=y;const out=(a,b)=>{points.push([a,b]);x=a;y=b};if(c==='M'){out(s[1],s[2]);sx=x;sy=y;}else if(c==='L')out(s[1],s[2]);else if(c==='H')out(s[1],y);else if(c==='V')out(x,s[1]);else if(c==='Z')out(sx,sy);else if(c==='C'){const ts=[0,1];for(const [a,b,c,d]of [[ox,s[1],s[3],s[5]],[oy,s[2],s[4],s[6]]]){let A=-a+3*b-3*c+d,B=2*(a-2*b+c),C=b-a;if(Math.abs(A)<1e-12){if(B)ts.push(-C/B);}else{let disc=B*B-4*A*C;if(disc>=0)ts.push((-B+Math.sqrt(disc))/(2*A),(-B-Math.sqrt(disc))/(2*A));}}for(const t of ts.filter(t=>t>=0&&t<=1)){let u=1-t;out(u*u*u*ox+3*u*u*t*s[1]+3*u*t*t*s[3]+t*t*t*s[5],u*u*u*oy+3*u*u*t*s[2]+3*u*t*t*s[4]+t*t*t*s[6]);}x=s[5];y=s[6];}else if(c==='Q'){let ts=[0,1];for(const[a,b,c]of[[ox,s[1],s[3]],[oy,s[2],s[4]]])if(a-2*b+c)ts.push((a-b)/(a-2*b+c));for(const t of ts.filter(t=>t>=0&&t<=1)){let u=1-t;out(u*u*ox+2*u*t*s[1]+t*t*s[3],u*u*oy+2*u*t*s[2]+t*t*s[4]);}x=s[3];y=s[4];}else throw Error(c);});return points;}
for(const name of names){const xml=fs.readFileSync(`assets/regular/${name}.svg`,'utf8'),dom=new JSDOM(xml,{contentType:'image/svg+xml'});let bounds=[Infinity,Infinity,-Infinity,-Infinity];for(const el of dom.window.document.querySelectorAll('path,rect,ellipse,circle')){let chain=[],n=el;while(n&&n.tagName!=='svg'){if(n.hasAttribute('transform'))chain.unshift(n.getAttribute('transform'));n=n.parentElement;}const tr=chain.join(' '),num=a=>Number(el.getAttribute(a)||0);let d;if(el.tagName==='path')d=el.getAttribute('d');else if(el.tagName==='rect'){let x=num('x'),y=num('y'),w=num('width'),h=num('height');d=`M${x} ${y}h${w}v${h}h${-w}Z`;}else{let x=num('cx'),y=num('cy'),rx=num(el.tagName==='circle'?'r':'rx'),ry=num(el.tagName==='circle'?'r':'ry');d=`M${x-rx} ${y}A${rx} ${ry} 0 1 0 ${x+rx} ${y}A${rx} ${ry} 0 1 0 ${x-rx} ${y}Z`;}
const margin=el.getAttribute('stroke')==='none'?0:.55;
for(const[x,y]of points(d,tr)){bounds[0]=Math.min(bounds[0],x-margin);bounds[1]=Math.min(bounds[1],y-margin);bounds[2]=Math.max(bounds[2],x+margin);bounds[3]=Math.max(bounds[3],y+margin);}}
if(bounds[0]<0||bounds[1]<0||bounds[2]>24||bounds[3]>24)bad.push({name,bounds});const colors=[...new Set(xml.match(/#[0-9a-f]{6}/g)||[])];if(colors.length>3||colors.some(x=>!['#f0e9f8','#d9c9ed','#aa8bcf'].includes(x)))throw Error(name+' colors');if(/NaN|Infinity/.test(xml))throw Error(name+' invalid');}
console.log(JSON.stringify({checked:names.length,outOfBounds:bad},null,2));if(bad.length)process.exitCode=1;
